{
    "CustomerConnectionPlugin": {
        "toolbar_msg": "Connect Customer"
    },
    "CustomerConnectionDialog": {
        "close_btn": "Close",
        "customer_connection": "Connect Customer",
        "create": "Create",
        "customer": "Customer",
        "pole": "Pole",
        "first_free_port": "First Free Port",
        "splitter": "Splitter",
        "wall_box_name": "Wall Box Name",
        "drop_cable_name": "Drop Cable Name",
        "drop_cable_count": "Drop Cable Count"
    },
    "VirtualWalkoutPlugin": {
        "toolbar_msg": "Virtual Walkout"
    },
    "VirtualWalkoutToolbar": {
        "previous": "Previous",
        "next": "Next",
        "play": "Play",
        "pause": "Pause",
        "reset": "Reset",
        "reverse": "Reverse path",
        "set_path": "Set path"
    }
}
