{
    "structureCheckerPlugin": {
        "structure_checker": "Structure API"
    },
    "equipmentCheckerPlugin": {
        "equipment_checker": "Equipment API"
    },
    "conduitCheckerPlugin": {
        "conduit_checker": "Conduit API"
    },
    "cableCheckerPlugin": {
        "cable_checker": "Cable API"
    },
    "connectionCheckerPlugin": {
        "connection_checker": "Connection API"
    },
    "customerConnectionPlugin": {
        "customer_connection": "Customer Connection"
    }
}
