{
    "nmt_samples": {
        "button_title": "DevRel Samples Palette"
    },
    "LRT": {
        "LRT": "Long Running Task (LRT)"
    },
    "bfTubeRenamePlugin": {
        "bf_tube_rename_title": "BF Tube Rename"
    },
    "ConduitCapacityPlugin": {
        "conduit_capacity_title": "Conduit Capacity"
    },
    "customerConnectionPlugin": {
        "customer_connection": "Customer Connection (JS)"
    },
    "pythonCustomerConnectionPlugin": {
        "python_customer_connection": "Customer Connection (Python)"
    },
    "LiveDocsPlugin": {
        "LiveDocsTitle": "Live Documentation"
    },
    "restApiPlugin": {
        "rest_api_title": "REST API"
    },
    "customTabPlugin": {
        "custom_tab_title": "Custom Tab Info"
    }
}
