{
    "nmt_samples": {
        "button_title": "Samples Menu"
    },
    "customerConnectionPlugin": {
        "title": "JavaScript Customer Connection",
        "customer_connection": "JS Customer Connection",
        "description": "This tool streamline the connection process of a customer to a pole.\n\nTo use the tool click on a pole and on an address and then click the 'Connect' button and the tool will automatically create the underlying equipment (if needed), the route, the cable, and connect the cable to the fiber splitter and terminal.\n\nYou can find the source code in the folder modules/custom/public/js/Samples/customer_connection_javaScript."
    },
    "pythonCustomerConnectionPlugin": {
        "python_customer_connection": "Python Customer Connection",
        "description": "This tool connects several Adresses to a pole in one single call a REST service associated with a Python Controller.\n\nTo use the tool click on a pole and on an address and then click the 'Connect' button and the tool will automatically create the underlying equipment (if needed), the route, the cable, and connect the cable to the fiber splitter and terminal.\n\nYou can find the source code in the folder modules/custom/public/js/Samples/PythonCustomerConnection."
    },
    "LRT": {
        "LRT": "LRT",
        "LRT_title": "Long Running Task",
        "description": "Long Running Task (LRT) description to be created."
    }
}
